name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install
      working-directory: ./webSite_Comunication  # Ensure this points to the directory containing your package.json

    - name: Build
      run: npm run build
      working-directory: ./webSite_Comunication  # This should match the directory containing your package.json and where your build script is meant to run

    - name: Deploy
      run: |
        git config --global user.name ${{ env.user_name }}
        git config --global user.email ${{ env.user_email }}
        git remote set-url origin https://${{ secrets.github_token }}@github.com/${{ env.repository }}
        git config --list  # Print out Git configurations for debugging
        npm run deploy
      working-directory: ./webSite_Comunication  # Again, ensure this is correct for the deployment script
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
